# Generated by Django 4.0.4 on 2022-06-27 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='water',
            old_name='User_id',
            new_name='user',
        ),
    ]
